### PR TITLE
migrate to @grafana/create-plugin

### LINKED ISSUE #178: Migrate to grafana create-plugin
After updating dependencies `yarn builds`  shows the following warning:

```
$ grafana-toolkit plugin:build

⚠  DEPRECATED. This command is deprecated and will be removed in v10. ⚠
Please migrate to grafana create-plugin https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin
```

* https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin#migrate-your-existing-plugin
* https://grafana.github.io/plugin-tools/docs/migrating-from-toolkit/

### PR DESCRIPTION
**Pull request by TheSpacyCat**
Closes #178

### CODE REVIEW

**Comment by BenediktSeidl** [comment]
* the test release did not work as expected, only source code download is available, but no package download.
    * there are also quite some warnings in the release ci run about `set-output`.
* the compatibilitycheck ci action, builds the plugin, although we already build it in a step before.
    * does it really need to build the plugin at all? it references files in `src/` on the commandline.
    * could we reuse the already built plugin?
* add a link to #178 in the commit message to close the issue.

**Comment by TheSpacyCat** [comment]
The release was an old test release in my private test repo. I published the actual one and it should be fine.

The compatibilitycheck check was scaffolded by the `create-plugin`. My guess for the additional build step would be that it is there, so it can run in parallel with the tests. I'll do some research to verify that, but is that worth it for us? My intuition would say 'no'.

Cleanup of warnings is a good idea, I'll also take care of the warnings about actions scripts that still use node 12.

**Comment by TheSpacyCat** [comment]
Grafana UI changed in 9.5. E2e tests will be adjusted in the next Sprint.

**Comment by TheSpacyCat** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by TheSpacyCat** [comment]
recheck

**Review by BenediktSeidl — APPROVED** [review]

**Pull request merged**
